// Legal.js

import React from "react";
import Link from "next/link";
import s from '@/components/legal.module.css';

const Legal = () => {
  return (
    <div>
      <div className={`${s.legalContainer}`}>
        <div className={`${s.legalPolicyText}`}>
          <h2 className="text-black">Legal Policies</h2>
          
          <ul className={`${s.legalLinks}`}>
            <li><Link href="/legal/terms-of-service">Terms of Service</Link></li>
            <li><Link href="/legal/privacy-policy">Privacy Policy</Link></li>
            <li><Link href="/legal/cookie-policy">Cookie Policy</Link></li>
          </ul>
        </div>

        <div className={`${s.legalPolicyContent}`}>
        <section id="top"></section>

        <h1 className="text-4xl mb-2">General Terms of Service</h1>
        <p className="mb-4">Last updated: July 1, 2023</p>
          <p><strong>INTRODUCTION</strong></p>
          <p><strong>General Terms.</strong></p>
          <p>Thank you for choosing us. Before starting, please read these General Terms of Service ("General Terms") carefully. Among other things, the General Terms cover the scope of your use of and access to the UnblockVPN services (the "Service" or "Services"). These General Terms also govern the use of and access to UnblockVPN's website ("Website").</p>
          <p><strong>Subscription.</strong></p>
          <p>All our paid Services are provided on a Subscription basis. This means that the provision of the Services will auto-renew at the end of the current Subscription period, unless you cancel it before the auto-renewal. For a summary of key aspects related to your Subscription of our Services, please read the Subscription Terms.</p>
          <p><strong>Terms.</strong></p>
          <p>These General Terms and the Subscription Terms, along with any applicable Service Specific Terms (see Section 2 of the General Terms below) (collectively, the "Terms").</p>
          <p><strong>UnblockVPN.</strong></p>
          <p>For the purpose of the Terms, "UnblockVPN," "we," "us," or "our" means UnblockVPN, a company registered at 188 Quay Street, Auckland, New Zealand.</p>
          <p><strong>Privacy.</strong></p>
          <p>For information about how we collect and process your personal data, please read our Privacy Policy.</p>
          <p><strong>YOUR AGREEMENT WITH UNBLOCKVPN</strong></p>
          <p><strong>Binding Legal Agreement.</strong></p>
          <p>Please note that the Terms constitute a binding legal agreement between you or those you legally represent ("you") and UnblockVPN. You agree and accept to be bound by these Terms by either: (i) creating a user account and/or other accounts to use Services ("Account"); (ii) downloading Software or accessing/using its Services and Website; or (iii) otherwise electronically agreeing to be bound by these Terms. If you are using the Services on behalf of an organization, you are agreeing to these Terms for that organization and acknowledging that you have the authority to act on behalf of that organization and commit to these Terms on behalf of that organization.</p>
          <p>OUR SERVICES ARE OFFERED TO YOU CONDITIONAL ON YOUR ACCEPTANCE OF THESE TERMS. PLEASE READ CAREFULLY ALL OF THEM. IF YOU DO NOT AGREE TO BE BOUND BY THESE TERMS OR ANY PROVISIONS HEREOF, PLEASE DO NOT ACCESS AND USE OUR SERVICES AND/OR WEBSITE.</p>
          <p><strong>Service Specific Terms.</strong></p>
          <p>Our certain Services require additional terms and conditions. Your use of our Services specified below is subject to the General Terms and Service Specific Terms ("Service Specific Terms"):</p>
          <p>&bull; UnblockVPN Additional Terms</p>
          <p>By using the Services, you also agree to the Service Specific Terms applicable to the respective Service(s). If there is any conflict or inconsistency between clauses in the Terms and Service Specific Terms, the Service Specific Terms govern and apply in relation to that specific Service(s).</p>
          <p><strong>Services.</strong></p>
          <p>Our Services are usually provided as paid Services. We also may offer a version of certain Services which is provided free of charge. The Terms apply to both types of Services.</p>
          <p><strong>Accessing the Services and/or Website.</strong></p>
          <p>You affirm that you are eighteen (18) or more years of age or have the authority to act on behalf of a valid legal entity, and you are fully able and have all rights and power to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms, and to abide by and comply with them.</p>
          <p><strong>Updates to the Terms.</strong></p>
          <p>We develop our Services and Website introducing new features or modifying current ones constantly. In addition, we may need to update the Terms by amending them from time to time (i) to comply with the law; (ii) to comply with orders/recommendations of regulatory authorities; (iii) to add additional functionality, services, features, technologies, and/or benefits, or to remove the old ones; (iv) to correct errors and bugs; (v) to clarify the Terms; (vi) to prevent abuse or harm; (vii) for any other valid reason (e.g., for security reasons). You understand and agree that it is your obligation to review the Terms from time to time in order to stay informed on current rules and obligations. Notification on any material changes to the Terms that affect your rights or obligations will be provided in advance of such changes by reasonable means (e.g., via email). Unless it is stated by us otherwise, each update of the Terms comes into force as of the moment when amended Terms are published. Your continued use of the Services will be deemed acceptance thereof. You can also end your relationship with us at any time after the effective date of the updated Terms by closing your Account and/or not accessing our Services and Website.</p>
          <p>THE TERMS MAY CHANGE, SO IT IS IMPORTANT TO REVIEW THE TERMS PERIODICALLY.</p>
          <p><strong>SUBSCRIPTION AND AUTO-RENEWALS </strong></p>
          <p><strong>Subscription.</strong></p>
          <p>All our paid Services are provided on a Subscription basis. You choose the period of Services and the payment method yourself when you purchase the Services. Please review Subscription Terms for more information.</p>
          <p><strong>Auto-Renewal.</strong></p>
          <p>After the end of your Service period, your Subscription will automatically renew for the successive defined Service periods at the renewal dates unless you decide to cancel the Subscription renewal before the day of the charge. If you do not cancel the Subscription in such due course, your chosen payment method will be charged the then-current renewal price for the upcoming defined Service period.</p>
          <p><strong>YOUR USER ACCOUNT</strong></p>
          <p><strong>Creating an Account.</strong></p>
          <p>To access and use any of our Services, you must set up an Account by providing certain information (e.g., your email address, password, billing information, country). All information you provide must be complete, accurate, true to the fact, and kept up to date. All UnblockVPN Accounts are non-transferable.</p>
          <p><strong>Confidentiality of and Access to the Account.</strong></p>
          <p>You agree to accept responsibility and are solely responsible for any and all usage and activities that occur under your Account or password, including, but not limited to, use of the Account by any other person, whether or not authorized by you. You are responsible for maintaining the confidentiality of your Account and its password, and for restricting access to your Account by any other party. To protect your Account, keep your password confidential. Do not reuse your Account password with other services. You agree to immediately notify us of any unauthorized use of your Account or password.</p>
          <p><strong>PRICES AND PAYMENTS </strong></p>
          <p><strong>Total Price.</strong></p>
          <p>Prices of our Services initially displayed to you may be provided exclusive of taxes. Due to the worldwide nature of our Services and mobility of consumers, we might not be able to identify the particular taxes applicable to you in advance. Therefore, we can calculate the additional mandatory taxes (e.g., sales tax, value-added tax, or another mandatory tax under laws applicable to you) only after you choose your tax residence country. In any case, we will display the sum of additional taxes applicable to your purchase along with the total price of your payment before charging you.</p>
          <p><strong>Payments.</strong></p>
          <p>You agree to pay us for any paid Services you purchase from us, as well as all other charges incurred under your Account, including applicable taxes and fees associated with your purchase of the Services. We may suspend or cancel the Services if we do not receive a full payment from you on time. Suspension or cancellation of the Services for non-payment could result in a loss of access to and use of your Account and its content.</p>
          <p><strong>Recurring Payments.</strong></p>
          <p>When you purchase the Services on a Subscription basis (e.g., monthly, annually, or otherwise), you agree that (i) Services will auto-renew until you cancel it, (ii) you are authorizing recurring payments, (iii) payments will be made to UnblockVPN by the method and at the recurring intervals you have agreed to, and (iv) when applicable, UnblockVPN may receive and use updated card account information from the financial institution that has issued your card (used to purchase the Services). For more information about the Subscription and its cancellation, please read our Subscription terms.</p>
          <p><strong>Payment Methods.</strong></p>
          <p>To purchase Services directly through us on our Website, you must provide us with a current and valid method of payment, such as a credit or debit card or any other payment method available on the Website.</p>
          <p><strong>Billing.</strong></p>
          <p>By providing UnblockVPN with a payment method, you (i) represent that you are authorized to use the payment method you provided and that any payment information you provide is true and accurate; (ii) authorize UnblockVPN to charge the payment method you provided; and (iii) authorize UnblockVPN to charge you for any paid Services you chose when making a purchase. You can view your billing history and manually generate the receipts and invoices for our Services at any time in your Account (log in to your Account, click the "Billing" button, and under Section "Billing history" generate the receipt/invoice by clicking "Get invoice"). If you have any questions related to payments, please contact us.</p>
          <p><strong>Payment Providers.</strong></p>
          <p>Purchases may be handled via multiple payment companies. To find out more on how payment companies process your personal data, please refer to our Privacy Policy.</p>
          <p><strong>Payment Processing.</strong></p>
          <p>UnblockVPN also reserves the right to (i) obtain and continue using updated credit card account information electronically, when applicable, from the card brands, (ii) retry failed payments to complete transactions, including but not limited to, retrying failed cards with extended expiration dates and, (iii) change or amend authorized payment companies to assist with payment processing.</p>
          <p><strong>Fraud Protection.</strong></p>
          <p>UnblockVPN reserves the right to verify credit/debit card payments prior to completing your purchase.</p>
          <p><strong>Change of Prices.</strong></p>
          <p>We may at our reasonable discretion change the price of our paid Services, including Subscription renewal prices, from time to time to reflect the changes of the total costs associated with our Services. Examples of cost elements that affect the price of our Services include licensing costs, costs for the technical provision and distribution, and other costs of sales (e.g., billing, marketing), general administration, and other overhead costs (e.g., rent, interest and other financing costs, costs of personnel, service providers and services, IT systems, energy), as well as state-imposed fees, contributions, taxes, and duties. Any changes to the pricing will not affect your current Subscription period and will become effective only upon the Subscription renewal. We will always send you a notification prior to charging with an upcoming payment amount. Subject to applicable law, (i) if you disagree with any proposed change of renewal price, your sole remedy is to cancel your Subscription before the next charge is made, and (ii) your continued use of the Services without canceling the Subscription constitutes your agreement to pay the new renewal price for the Services.</p>
          <p><strong>Changes of Payment Details.</strong></p>
          <p>If any of your payment details change (like card number or its expiry date), please let us know as soon as possible so we can continue to provide the Services when it comes time for the Subscription renewal. If you update payment details in your Account, the updated information will be regarded as your preferred method for any future payments. Sometimes we may receive updated credit or debit card information from your card issuer or the card network, which UnblockVPN will use to update your payment details automatically.</p>
          <p><strong>Free Trials.</strong></p>
          <p>In some cases, we or others on our behalf may offer a free trial for our paid Services prior to charging your payment method (&ldquo;Free Trial&rdquo;). The duration of the Free Trial, its use and other details will be specified during sign-up and/or in the promotional materials. We determine your Free Trial eligibility at our sole discretion, and to the extent permitted under applicable law, we may limit or withdraw the Free Trial option at any time without notice. If you provide your payment details when signing up for the Subscription with a Free trial, we will automatically charge you for the Subscription of our paid Services, and it will auto-renew until canceled. If you do not want to continue with a paid Subscription after the Free Trial, you must cancel it before the end of the Free Trial. If you received the Free Trial from a third party, you may cancel the paid Subscription through that third party. We reserve the right to limit you to one free trial or promotion of a paid Service and to prohibit the combining of free trials or other promotional offers.</p>
          <p><strong>CANCELLATION AND REFUND POLICY</strong></p>
          <p><strong>Subscription Cancellation.</strong></p>
          <p>You have the right to cancel your Subscription (i.e., turn off auto-renewals for the upcoming Service period) at any time (please note that canceled Subscriptions will not be refunded for the unused part of the ongoing Service period). Your possibilities to cancel the Subscription and/or get a refund may differ depending on whether you purchased Services from (or are billed through) UnblockVPN or a third party (e.g., app store, service provider, retailer).</p>
          <p><strong>Refund.</strong></p>
          <p>We seek your full satisfaction with our Services. However, if you are not satisfied with our Services, you may cancel the Subscription and request a refund within thirty (30) days following your purchase of our Services (&ldquo;Money Back Guarantee&rdquo;). Please note that we do not grant Money Back Guarantee for the auto-renewed Subscription if you cancel the Subscription after the day of charge for such auto-renewal unless applicable law provides otherwise. In any case, we would be glad to troubleshoot an issue you experienced before you decide to request a Money Back Guarantee.</p>
          <p><strong>Payment of Refund.</strong></p>
          <p>Your request will be processed without any unreasonable delay, and the refund will be paid using the same payment method as the one used for the purchase, except as otherwise mutually agreed unless applicable law prohibits us or payment service providers we rely on from processing the refund. For payments made in cryptocurrency, the refund will be made in the same cryptocurrency or in another cryptocurrency if the one used for the purchase becomes unavailable or impracticable to use. The amount to be refunded in cryptocurrency will be calculated based on the equivalent of the price paid in USD at the time of purchase. Payments made using prepaid cards or gift cards will not be refunded if such a refund is not supported by the provider of the card. Once the refund is issued to you, you will lose access to the Services for which you were refunded.</p>
          <p><strong>Eligibility for Refund.</strong></p>
          <p>You can only get a refund for each of our Services under the Money Back Guarantee twice. If you buy a particular Service again after the second refund for such Service, you will not be granted a Money Back Guarantee for any of its further cancellation. In case you cancel your Subscription at any time after the expiration of the respective Money Back Guarantee period, you shall be charged for the whole Subscription's duration (e.g., if you purchase an annual Subscription and you decide to cancel your Subscription after two (2) months, you will be charged the whole price, but once the Subscription has ended, it will not be renewed).</p>
          <p><strong>Subscriptions Purchased via Apple App Store.</strong></p>
          <p>Subscriptions purchased via the Apple App Store are subject to Apple App Store refund policies. This means we cannot grant a refund if you made a purchase through the Apple App Store - please read Apple's in-app purchase refund policy and/or contact store support. If you purchased an automatically renewing Subscription through the Apple App Store and would like to cancel it, you will need to do so in your Apple App Store account directly. Instructions can be found here: <a href="https://support.apple.com/en-gb/HT202039#third_party" target="_blank" rel="noopener">https://support.apple.com/en-gb/HT202039#third_party</a>.</p>
          <p><strong>Subscriptions Purchased via other Providers.</strong></p>
          <p>The refunds for purchases made from third-party marketplaces, retailers, and resellers (Amazon, BestBuy, StackSocial, etc.) are handled according to the terms of service of the providers from which the Services were purchased. Cancellation of such Subscriptions may also be subject to the terms of certain providers.</p>
          <p><strong>Canceling the Auto-Renewal of the Subscription Purchased on our Websites.</strong></p>
          <p>If you have purchased an automatically renewing Subscription on our Websites and would like to stop it from automatically renewing, you can do so at any time from your UnblockVPN Account. Canceled Subscriptions will not be refunded for the unused part of the ongoing Service period.</p>
          <p>LICENSE TERMS</p>
          <p><strong>Software.</strong></p>
          <p>To access and use our Services, you may be required to download and install our Software on a device. Below, see the terms and conditions applicable to the use of such Software. Pursuant to these Terms, &ldquo;Software&rdquo; means any mobile and desktop software applications and any other software (including any releases, updates, enhancements, or revisions) and any documentation that accompanies or is made available in connection with such software provided by us to you for your use of the Services.</p>
          <p><strong>License Grant.</strong></p>
          <p>Subject to the terms and conditions of these Terms and provided that you comply with the Terms, we grant you a limited, revocable, non-exclusive, personal, non-transferable, non-sublicensable, non-assignable, fixed-term license (the &ldquo;License&rdquo;) to download, install and use a copy of the Software on a compatible device that you own or control. No other right or license, express or implied, of any kind is granted to you hereunder with respect to the Services and/or Software.</p>
          <p><strong>Apple Requirements.</strong></p>
          <p>For the sake of clarity, in respect to the Software that is downloaded from Apple, Inc. (&ldquo;Apple&rdquo;) App Store, the License is limited to the use of such Software on any Apple-branded devices that you own or control and as permitted by the Usage Rules set forth in the Apple Media Services Terms and Conditions, except that such Software may be accessed and used by other accounts associated with you via family sharing or volume purchasing features.</p>
          <p><strong>We Retain all Rights.</strong></p>
          <p>The Software, used pursuant to these Terms, is licensed, not sold, and you receive no title to or ownership of any copy or of the Software itself, or even more so of the Services and Websites. You receive no rights to the Software other than those specifically granted in Section 7.2. We and/or our licensors retain all right, title, and interest in and to the Services, Software, Websites, and any portion thereof. All rights are reserved unless otherwise explicitly expressed. UnblockVPN, Unblock Security, UnblockVPN.io, and other UnblockVPN trademarks are protected trademarks, owned by UnblockVPN, and you are forbidden from registration, adoption, or any other use of trademarks, trade names, symbols, or signs that are either identical or confusingly similar to any trademarks owned by UnblockVPN.</p>
          <p>The version of the Services and Software available at your renewal date may be different from the version available when you first purchased your License from us. We provide application updates for all OS versions for at least two (2) years after the initial OS version release.</p>
          <p><strong>Feedback.</strong></p>
          <p>You hereby grant UnblockVPN and/or its affiliated companies a perpetual, irrevocable, worldwide license to use Feedback (as defined below) you communicate to us without reimbursement or compensation, without any obligation to report on such use, and without any other restriction. You waive (or agree not to enforce) any and all rights that may now or in the future exist (including moral and equivalent rights) in Feedback. (&ldquo;Feedback&rdquo; refers to any recommendation, idea, proposal, suggestion, feedback, review, or other input related to our Services, Software, Websites)</p>
          <p><strong>PROHIBITED AND RESTRICTED USE</strong></p>
          <p>Your access to and use of the Services and Websites are subject to the Terms and all applicable laws and regulations. We reserve the right, at any time, in our sole discretion, with or without notice, to suspend and/or terminate the Accounts and/or Services to any users who violate any applicable laws or these Terms, whether repeated violation or a single instance. Please read more information in Section 12 of the General Terms (&ldquo;Suspension and Termination&rdquo;).</p>
          <p>You agree that you shall not yourself and/or enable others to:</p>
          <ul>
          <li>Use, assist, encourage, or enable others to use the Services/Websites for any unlawful, illicit, illegal, criminal, or fraudulent activities, including but not limited to port scanning, sending spam, sending opt-in email, scanning for open relays or open proxies, sending unsolicited email or any version or type of email sent in vast quantities even if the email is routed through third-party servers, any pop-up launching, use of stolen credit cards, credit card fraud, financial fraud, cryptocurrency fraud, cloaking, extortion, blackmail, kidnapping, rape, murder, sale of stolen credit cards, sale of stolen goods, offer or sale of prohibited and dual-use goods, offer or sale of controlled substances, identity theft, hacking, pharming, phishing, scraping in any form or scale, digital piracy, conduct distributed denial-of-service (DDoS) attacks, and other similar activities;</li>
          <li>Use the Services/Websites for any military purpose, including cyber warfare, weapons development, design, manufacture, or production of missiles, nuclear, chemical or biological weapons;</li>
          <li>Assault, interfere, gain unauthorized access, deny service in any way or form to any other network, computer, or node through our Services/Websites;</li>
          <li>Exploit children in any way, including audio, video, photography, digital content, etc.;</li>
          <li>Violate, infringe, or misappropriate UnblockVPN, our licensors and/or any other third parties' copyright, other intellectual property rights, privacy, or other legal rights;</li>
          <li>Communicate, transmit, store, make available, share anything that is illegal, abusive, harassing, or otherwise objectionable (objectionable means anything that interferes with the rights of UnblockVPN, its users, or other third parties or causes conditions that are dangerous, hazardous, and detrimental to others or anything that most users and/or UnblockVPN would find to be offensive or inappropriate);</li>
          <li>Transmit any viruses or other computer codes, files, programs, instructions, or technological means that disrupt, damage, or interfere with the use of computers or related systems;</li>
          <li>Attempt to circumvent any technological measure and/or arrangement implemented by UnblockVPN and/or its licensors or by the owner of the resource or the source of the material that the technological measure protects;</li>
          <li>Interfere with or disrupt the integrity or performance of the Service/Websites;</li>
          <li>Take any action that imposes or may impose an unreasonable or disproportionately large load on our infrastructure;</li>
          <li>Sublicense, sell, resell, transfer, assign, distribute, or otherwise commercially exploit or make available to any third party the Services, Subscription, and/or Account in any way;</li>
          <li>Use any robot, spider, scraper, or other automated means to access our Websites or Services for any purpose without our prior written permission;</li>
          <li>Build a product using similar ideas, features, functions, or graphics of the Service/Websites or copy any ideas, features, functions, or graphics of the Services/Websites;</li>
          <li>Claim that you are the representative or agent of any of the Services, including any of its functionality;</li>
          <li>Threaten, stalk, harm, or harass others or promote bigotry or discrimination;</li>
          <li>Attempt to gain unauthorized access to the Services, Accounts, computer systems, or networks connected to the Services through hacking, password mining, brute force, or any other means;</li>
          <li>Violate general ethical or moral norms, good customs, and fair conduct norms;</li>
          <li>Use the Services/Websites for anything other than lawful purposes;</li>
          <li>Consistently demonstrate disrespectful, threatening, offensive, and/or malicious behavior when communicating with UnblockVPN customer support and/or other employees;</li>
          <li>Access and use the Services if you have been or are prohibited from accessing the Services or if your Account has been suspended or terminated due to any reason;</li>
          <li>Share non-public features or content of the Software and/or Services with any third party;</li>
          <li>To the extent permitted under applicable law, otherwise violate or attempt to evade or circumvent these Terms.</li>
          </ul>
          <p>You also shall not take any action to jeopardize, limit, or interfere in any manner with our ownership and rights with respect to the Services. Except and to the extent that this is expressly permitted by applicable law and these Terms, you receive no right to and shall not yourself or enable others to:</p>
          <ul>
          <li>Reproduce, modify, create derivative works from, distribute, make available over a network, publicly display, or publicly perform the Services, Software, or Websites;</li>
          <li>Reverse engineer, decompile, disassemble, decrypt the Software, Services, Websites, or make any attempt to derive the code, trade secrets, or other confidential information from the Services, Software, Websites;</li>
          <li>Translate, adapt, arrange, or make any other alteration of the Services, Software, Websites, and reproduce the results thereof;</li>
          <li>Transfer, distribute, lease, sublicense, or rent the Services, Software, Websites, and/or your rights granted under the License to any third party;</li>
          <li>Use the Services, Software, Websites in any manner that is not expressly permitted pursuant to the Terms;</li>
          <li>Remove or modify markings or any notice of proprietary rights of the Services, Software, Websites.</li>
          </ul>
          <p>We use automated tools to identify web scraping and minimize abuse of our Services. These tools are looking for irregular patterns when new sessions are initiated, and if such patterns are noticed, it might automatically suspend your Account or otherwise limit your access to the Services until further investigation is complete.</p>
          <p>It is your responsibility to comprehend the relevant laws related to any jurisdiction or venue that concerns you, your actions, and your use of the Services. You access and use the Services in your country on your initiative, and you solely are responsible for complying with your local laws and regulations and the laws and regulations of any country with which or through which you communicate, transmit, or receive data, if and to the extent such laws are applicable.</p>
          <p>We encourage you to let us know about the violation of these Terms by any of UnblockVPN users or other third parties by contacting us (Section 18 of these General Terms (&ldquo;Contact Us&rdquo;). In case of such violations, we may take appropriate action at our sole discretion.</p>
          <p><strong>DISCLAIMER OF WARRANTIES</strong></p>
          <p>Reasonable efforts are taken to improve the accuracy and integrity of the Services, but complex software is never wholly free from defects, errors, and bugs. We give no warranty or representation that the Services will be wholly free from defects, errors, and bugs, such as downtime, loss of data, corrupt data, service delay, mistakes, out-of-date information, or other. Notwithstanding any other provision of the Terms, we reserve the right to modify, suspend, or terminate access to the Services, or any functionality comprising a part of the Services at any time. In no event, to the extent permitted under applicable law, will we be liable for making these changes. In exceptional and very limited cases, our Services may be unavailable from time to time due to human, digital, mechanical, telecommunication, software, and other failures. We cannot predict or control when such downtime may occur and cannot control the duration of such downtime.</p>
          <p>THE SERVICES AND WEBSITES ARE PROVIDED &ldquo;AS IS&rdquo; AND WITH ALL FAULTS. WE MAKE NO REPRESENTATION OR WARRANTY WHATSOEVER REGARDING THE COMPLETENESS, ACCURACY, ADEQUACY, SUITABILITY, FUNCTIONALITY, AVAILABILITY, OR OPERATION OF THE SERVICES. YOU ACKNOWLEDGE THAT WE DO NOT HAVE CONTROL OVER YOUR USE OF THE SERVICES, AND WE DO NOT WARRANT THE PERFORMANCE OR RESULTS THAT MAY BE OBTAINED THROUGH YOUR USE OF THE SERVICES. YOU ASSUME ALL RISKS AND RESPONSIBILITY FOR YOUR USE OF THE SERVICES AND FOR ANY LOSS OF OR ERRORS IN ANY DATA OR INFORMATION. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT, AND ANY WARRANTIES ARISING THROUGH COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE. WITHOUT LIMITING THE FOREGOING, WE NEITHER WARRANT NOR REPRESENT THAT YOUR USE OF THE SERVICES WILL NOT INFRINGE THE RIGHTS OF ANY THIRD PARTIES, NOR THAT THE SERVICES WILL BE AVAILABLE FOR YOUR ACCESS OR USE, NOR THAT OPERATION OF THE SERVICES WILL BE ERROR-FREE OR UNINTERRUPTED. PLEASE NOTE THAT SOME JURISDICTIONS MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. IN ADDITION, YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM ONE JURISDICTION TO ANOTHER JURISDICTION.</p>
          <p><strong>LIMITATION OF LIABILITIES</strong></p>
          <p>There are inherent risks in relying upon, using, transmitting, or retrieving any data and/or content on the internet, and we urge you to make sure you understand these risks before using the Services. UnblockVPN disclaims all responsibility for the behavior of its users and/or visitors when they access or use the Services/Websites.</p>
          <p>YOUR USE OF THE SERVICES AND WEBSITES IS AT YOUR OWN RISK. NEITHER UNBLOCKVPN, NOR ANY OF ITS PARENTS, SUBSIDIARIES OR AFFILIATES, NOR ANY OF THEIR EMPLOYEES, OFFICERS OR DIRECTORS, SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR OTHER DAMAGES (INCLUDING, WITHOUT LIMITATION, LOSS OF DATA OR INFORMATION OF ANY KIND, LOSS OF BUSINESS, LOST PROFITS, INTERRUPTION OF BUSINESS, COST OF COVER OR ANY OTHER DAMAGES) ARISING OUT OF OR IN ANY WAY RELATED TO THESE TERMS OR THE USE OR INABILITY TO USE THE SERVICES OR WEBSITES, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN ANY CASE, THE TOTAL AGGREGATE LIABILITY OF UNBLOCKVPN ARISING OUT OF OR RELATING TO THESE TERMS SHALL NOT EXCEED WHAT YOU PAID TO UNBLOCKVPN DURING TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO SUCH LIABILITY AND SHALL NOT INCLUDE ATTORNEY FEES OR COURT COSTS IRRESPECTIVE OF ANY LAWS OR STATUTES THAT MAY PRESCRIBE OTHERWISE. YOU ACKNOWLEDGE THAT THE AMOUNT OF FEES PAYABLE BY YOU TO UNBLOCKVPN HEREUNDER REFLECT THE ALLOCATION OF RISK SET FORTH IN THE TERMS AND THAT UNBLOCKVPN WOULD NOT HAVE ENTERED INTO THE AGREEMENT WITH YOU WITHOUT THE LIMITATIONS ON ITS LIABILITY CONTAINED IN THIS SECTION.</p>
          <p>Some jurisdictions restrict or do not allow the limitation of liability in contracts (e.g., limitation of liability for death or personal injury caused by other party's negligence, fraud, or fraudulent misrepresentation, willful misconduct, or gross negligence). As a result, respective provisions of this Section may not apply to you. In cases where such restrictions on the limitation of liability apply, the liability of UnblockVPN shall be limited to the fullest extent permitted by certain applicable law.</p>
          <p>Please also note that UnblockVPN has implemented security measures aimed at securing the Services and Websites; nevertheless, the internet is not a secure network and system reliability could be impaired independently of UnblockVPN's efforts and will. In addition, UnblockVPN cannot be held liable for unpredictable events such as cyber attacks, security breaches regarding the transmission of data or for performance guarantees regarding the volume and speed of data transmissions. Users are responsible for taking all appropriate measures to protect their own data, software, equipment, and systems, particularly from contamination by any viruses circulating on the internet.</p>
          <p><strong>INDEMNIFICATION</strong></p>
          <p>You agree, at your own expense, to indemnify, defend, and hold harmless UnblockVPN, its parents, subsidiaries, and affiliates and their officers, directors, employees, agents, distributors, and licensees from and against any judgments, losses, deficiencies, damages, liabilities, costs, claims, demands, suits, and expenses (including, without limitation, reasonable attorneys' fees, expert witness fees, and expenses) incurred in, arising out of or in any way related to (i) your breach of these Terms; (ii) your (or any other user's of your Account) use of the Services; (iii) your violation of any applicable laws, rules, and regulations; or (iv) your negligence or willful misconduct. UnblockVPN shall not be responsible for any delay or disruption to your use of the Services, including any damages stemming therefrom, caused by circumstances falling under this Section.</p>
          <p><strong>SUSPENSION AND TERMINATION</strong></p>
          <p>Suspension and Termination by UnblockVPN. We may suspend (for clarification, investigation, or when requesting you to explain your actions) or terminate your Account and/or Services if (i) we cannot charge you for the auto-renewed Subscription, (ii) you breach Section 8 of the General Terms ("Prohibited and Restricted Use"), (iii) you breach any applicable laws, (iv) it is required to do so by law or competent authority (e.g., where the provision of the Services becomes unlawful in your country of residence, or final court judgment bearing relation to your use of our Services, Software, or Websites is issued).</p>
          <p>If the situation warrants, we will give you a reasonable opportunity to fix the issue before suspending or terminating your Account and/or Services. However, if your Account has been suspended, you must contact us for further information. We may (but have no obligation) suspend your Account for a reasonable period of time before we terminate it permanently.</p>
          <p>Usually, we will send you a prior notice before suspending or terminating your Account and/or Services. However, under limited circumstances, we will be unable to send a notice to you prior to terminating your access to our Services if: (i) you are in material breach of Section 8 of the General Terms ("Prohibited and Restricted Use") or any applicable laws in such a way as to immediately and seriously endanger us and/or any other third party or cause disruption to our Services; (ii) we are unable to send you notice because you have not provided or properly updated your contact details; (iii) we are unable to notify you due to the requirements of law and/or orders of the authorities.</p>
          <p>Any suspension or termination of your Account and/or Services by UnblockVPN applies to you personally; you may not access our Services through any other Account that you own or create or through Accounts owned or created by others.</p>
          <p><strong>Termination by You.</strong></p>
          <p>You may cancel the Services at any time as set forth in Section 6 of the General Terms ("Cancellation and Refund Policy"). On how to terminate (delete) your Account, please read our Privacy Policy.</p>
          <p><strong>Effects on Suspension or Termination.</strong></p>
          <p>Upon suspension or termination under these Terms, you will lose access to the Services, and you shall cease all use of the Software. Upon expiration of your Subscription or any termination under these Terms, the License granted in Section 7.1 of these General Terms and any other licenses, if any, will immediately terminate without further notice from us. Therefore, you shall cease all use of the Software and Services, as well as delete, destroy, or return all copies of the Software in your possession or control.</p>
          <p><strong>Survival of Termination.</strong></p>
          <p>Sections 7-17 of the General Terms will survive termination or expiration of the Terms for any reason, as well as any other Sections of these Terms that, either explicitly or by their nature, must remain in effect even after termination or expiration of these Terms.</p>
          <p><strong>APPLICATION PLATFORM TERMS</strong></p>
          <p><strong>App Store.</strong></p>
          <p>If you downloaded our Software from Apple App Store or if you are using such Software and our Services on any Apple-branded device, you acknowledge that you have read, understood, and agree to the following notice regarding Apple:</p>
          <p>These Terms are concluded between you and UnblockVPN, not with Apple, and Apple is not responsible for the Services and the content thereof. If you need any support with respect to our Services, please contact us, not Apple, as they are under no obligation whatsoever to furnish any maintenance or support services with respect to our Services. To the extent that the Services fail to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the Service to you; to the maximum extent permitted by law, Apple will have no other warranty obligation with respect to the Services. Apple is not responsible for addressing any claims by you or any third party relating to the Service or your possession and/or use of the Service, including: (i) product liability claims; (ii) any claim that the Service fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation. Apple is not responsible for the investigation, defense, settlement, and discharge of any third-party claim that the Service and/or your possession and use of the application infringe that third party's intellectual property rights. You agree to comply with any applicable third-party terms when using the Service. Apple and Apple's subsidiaries are third-party beneficiaries of these Terms, and upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third-party beneficiary of these Terms. You hereby represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo or that has been designated by the U.S. Government as a "terrorist supporting" country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.</p>
          <p><strong>Other Stores.</strong></p>
          <p>If our Software is downloaded from any other store, platform, marketplace (e.g., Google Play, Amazon Appstore, Microsoft Store, HUAWEI AppGallery), you acknowledge that you have read, understood, and agree to the customer terms of use of such stores, platforms, and marketplace. UnblockVPN is the licensor of the Software and the provider of the Services, and any third party (e.g., operator of the store, platform, marketplace) is not a party to these Terms.</p>
          <p><strong>BUNDLED SUBSCRIPTIONS AND THIRD-PARTY SERVICES</strong></p>
          <p><strong>Bundled Subscriptions.</strong></p>
          <p>You may purchase a Subscription of UnblockVPN Service bundled with the Subscription of other UnblockVPN Service and/or a subscription of Third-Party Services (as described below) ("Bundled Subscriptions").</p>
          <p><strong>Third-Party Services Purchased through UnblockVPN.</strong></p>
          <p>We may offer to purchase third-party products and/or services independently (as a standalone service) or along with our Services (as a Bundled Subscription) through UnblockVPN ("Third-Party Services"). In all cases, your billing relationship for such services will be directly with UnblockVPN, and any fees charged for it will be billed by us using your provided payment method. Please note that Third-Party Services are governed not only by these Terms but also by terms of use issued by such third parties respectively (which you also accept by purchasing Third-Party Services through UnblockVPN). Please review the terms of use and other policies of Third-Party Services carefully and make sure you understand them before you purchase them through UnblockVPN. After you complete your purchase of Third-Party Services through UnblockVPN, you may need to follow additional instructions to create a separate account for subscription to and use of them. If there is any conflict or inconsistency between the terms of use of Third-Party Services and these Terms concerning Subscription purchase, auto-renewals, prices/payments, and cancellation/refunds, these Terms govern and apply.</p>
          <p><strong>Cancellation of Bundled Subscription/Third-Party Services.</strong></p>
          <p>You may cancel your Bundled Subscription/Third-Party Services (i.e., turn off auto-renewals for the upcoming Service period) at any time. By canceling your Bundled Subscription, you will lose access to all Bundled Services (i.e., if you wish to cancel, the only option is to cancel all UnblockVPN Services and Third-Party Services purchased as a Bundled Subscription; you cannot cancel only one or some of the Services, leaving the others active for the upcoming period).</p>
          <p><strong>UnblockVPN Services Purchased through Third Parties.</strong></p>
          <p>You may purchase UnblockVPN Services along with third-party service as a bundled subscription offered by third parties. Please review the terms of use and other policies of third-party bundled subscriptions carefully and make sure you understand them before you purchase such bundled subscription through third parties.</p>
          <p><strong>CONTRACTING ENTITY</strong></p>
          <p>The entity with which you are contracting under these Terms is UnblockVPN S.A.</p>
          <p><strong>GOVERNING LAW AND DISPUTE RESOLUTION</strong></p>
          <p><strong>Governing Law.</strong></p>
          <p>These Terms will be governed by the law of Panama except for its conflicts of laws principles. However, some countries (including countries of the European Union) have laws that require contracts to be governed by the mandatory provisions of the local laws of the consumer's country. In such cases, mandatory provisions of the local laws of your country of residence apply.</p>
          <p><strong>Out-of-Court Resolution of Disputes.</strong></p>
          <p>We always strive to address your concerns without needing a formal legal case. Before filing a claim against UnblockVPN, please try to resolve the dispute informally by sending us a written notice of dispute at support@unblockvpn.io that includes your name, a detailed description of the dispute, and the relief you seek. We will try to resolve the dispute informally by contacting you via email. If a dispute is not resolved, you or UnblockVPN may bring a formal proceeding.</p>
          <p><strong>Judicial Resolution of Disputes.</strong></p>
          <p>You and UnblockVPN agree that any judicial proceeding to resolve claims relating to the Terms will be brought in the courts of Panama. If you reside in a country (including countries of the European Union) where laws provide consumers the right to bring disputes in their local courts, in such cases, mandatory provisions of the local laws of your country of residence apply.</p>
          <p><strong>Online Dispute Resolution in the EU.</strong></p>
          <p>If you are a consumer, you may report the dispute to a consumer dispute body in your country of residence, in accordance with local regulations and practices. If you reside in the European Economic Area or Switzerland, the European Commission provides for an online dispute resolution platform, which you can access here:<a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener"> https://ec.europa.eu/consumers/odr</a>.</p>
          <p><strong>CLASS ACTION WAIVER</strong></p>
          <p>PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT.</p>
          <p>WHERE PERMITTED UNDER APPLICABLE LAW, YOU AND UNBLOCKVPN AGREE THAT EACH SHALL ONLY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION. Unless both you and UnblockVPN agree, no arbitrator or judge shall consolidate more than one person's claims or otherwise preside over any form of a representative or class proceeding.</p>
          <p><strong>MISCELLANEOUS</strong></p>
          <p><strong>Availability of Services.</strong></p>
          <p>Actual coverage, speeds, locations, and quality of Services may vary. UnblockVPN attempts to improve and provide Services at all times. However, our Services may be not available without prior notice or UnblockVPN's liability, including when (i) we test, update, expand, add, or remove our Services, features, functionalities, including those required to reflect changes in relevant laws and regulatory requirements; (ii) we experience temporary interruptions due to technical difficulties, maintenance or human errors; (iii) events beyond our control (e.g., events in nature and other force majeure events) happen.</p>
          <p><strong>Modification and Termination of Services.</strong></p>
          <p>We reserve the right to modify or update the operation of the Services at our sole discretion, at any time, for any reason, and without notice or liability. We may also suspend the Services entirely, in which event we will notify you in advance unless extenuating circumstances, such as safety or security concerns, prevent us from doing so. If you have prepaid fees directly to UnblockVPN for a paid Subscription that UnblockVPN permanently discontinues prior to the end of its period, UnblockVPN will refund you the pro rata part of such prepaid fees for the period after such discontinuation (except for cases referred to in Section 12.1 of these General Terms), and in such a case, your Account and billing information must be up to date to enable us to refund you. UnblockVPN has no liability to you, nor any obligation to provide a refund to you, in connection with internet or other service outages or failures that are caused by the actions of the authorities, other third parties, or events beyond our control.</p>
          <p><strong>Severability.</strong></p>
          <p>If any provision of the Terms is found to be unenforceable or invalid by any competent authority, that provision shall be limited or eliminated to the minimum extent necessary so that other provisions of the Terms shall otherwise remain in full force and effect and enforceable.</p>
          <p><strong>Assignment.</strong></p>
          <p>You may not assign these Terms or any rights or interest under these Terms or delegate any obligations to be performed under these Terms without UnblockVPN's prior written consent. UnblockVPN can assign, transfer, delegate any of its rights and obligations under these Terms to selected third parties without your consent, including but not limited to cases of corporate reorganization, merger, acquisitions, sale, or transfer of all or substantially all company assets. Notification of any material changes that affect your rights or obligations will be provided to you by reasonable means (e.g., via email).</p>
          <p><strong>Data Charges.</strong></p>
          <p>You are responsible for any charges that may apply to your use of our Services or Websites, including text messaging and data charges if you access or use the Services or Websites on your mobile or other device. If you're unsure what those charges may be, you should ask your mobile operator, internet, or other service provider before using the Services/Websites.</p>
          <p><strong>Third-Party Components.</strong></p>
          <p>You acknowledge that our Services, Software, and Websites may incorporate, embed, be combined with, or may otherwise interact with third-party computer programs, applications, services, links, and components ("Third-Party Components"). For the avoidance of doubt, Section 9 ("Disclaimer of Warranties") and Section 10 ("Limitation of Liabilities") of these General Terms apply to the foregoing interaction with Third-Party Components. Where our Websites contain links to other websites and/or resources provided by third parties, which include third-party social media websites such as Facebook, Instagram, and LinkedIn, they are provided for your information only. Please review the third-party website's terms of use and other policies carefully and make sure you understand them before you engage in any transaction.</p>
          <p><strong>Linking to our Websites.</strong></p>
          <p>You may link to our Websites, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval, or endorsement on our part where none exists.</p>
          <p><strong>Communication with UnblockVPN.</strong></p>
          <p>You may provide notices, requests, information, and other communications to UnblockVPN via our customer support. You agree to receive communications from us electronically, e.g., by email, through our applications, and customer support platforms and consent that such notifications have the same legal power as communication in writing. We may communicate with you to advise you about provision, changes, or additions to the Services or for other purposes that are reasonable or required by applicable law. When communicating with our customer support representatives, you agree to be respectful and kind. In addition, you undertake to provide accurate data for communication with us and, if your contact details have changed, update them in your Account immediately. UnblockVPN is not liable if you do not receive certain notices regarding the Services upon your failure to update your contact details.</p>
          <p><strong>Internet Connection.</strong></p>
          <p>Certain Services may require an active and stable connection to the internet to function. It is therefore your responsibility to ensure that you have at all times an active and stable internet connection.</p>
          <p><strong>Export Laws.</strong></p>
          <p>UnblockVPN products may be subject to the United States (U.S.) and European Union export and re-export control laws and regulations or similar laws applicable in other jurisdictions, including the Export Administration Regulations ("EAR") maintained by the U.S. Department of Commerce. You warrant that you are (i) not located in any country to which the U.S., the European Union, the United Kingdom, or other applicable jurisdiction (collectively, "Applicable Jurisdictions") has embargoed goods or services; (ii) not identified as a sanctioned party or restricted party by an Applicable Jurisdiction; (iii) not engaged in activities or transactions that may violate any applicable export control or economic sanctions laws or regulations; and (iv) not using the Software, Services, or Websites in connection with the design, development, or production of nuclear, chemical, or biological weapons, or rocket systems, space launch vehicles, or sounding rockets, or unmanned air vehicle systems (including cruise missiles, drones, and unpiloted aerial vehicles). You agree to comply strictly with all Applicable Jurisdiction's export control laws and regulations and assume sole responsibility for obtaining licenses to export or re-export as may be required. You shall indemnify and hold us harmless from and against any violation of these provisions. You expressly assume responsibility for verifying that you are in compliance with all applicable laws related to the export or re-export of the Software, Services, or Websites.</p>
          <p><strong>Entire Agreement.</strong></p>
          <p>These General Terms, including the incorporated documents referred to herein (including, but not limited to, the Privacy Policy), constitute the entire agreement between UnblockVPN and you concerning the subject matter hereof and supersede all prior or contemporaneous communications, understandings, and agreements between UnblockVPN and you, whether oral or written, regarding such subject matter.</p>
          <p><strong>Language.</strong></p>
          <p>The English version of these General Terms is the controlling version and shall prevail in the event of any discrepancy between the English version and any translated versions.</p>
          <p><strong>Contact Information.</strong></p>
          <p>If you have any questions or need further information regarding these General Terms, please contact us at support@unblockvpn.io.</p>
          <p>Thank you for taking the time to read our Terms of Service. If you have any further questions, please don't hesitate to ask.</p>

        </div>
      </div>
    </div>
  );
};

export default Legal;
